FROM node:16-alpine3.12

WORKDIR /app

RUN npm install -g npm@8.3.0

COPY ./package.json .
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .

CMD ["npm" ,"run", "start"]
